//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTFPrice_HTFTeam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Category
    {
        public Category()
        {
            this.Product_Category_Mappings = new HashSet<Product_Category_Mappings>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Danh mục")]
        public string Name { get; set; }
        public string Description { get; set; }
        public int ParentCategoryId { get; set; }
    
        public virtual ICollection<Product_Category_Mappings> Product_Category_Mappings { get; set; }
    }
}
