//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTFPrice_HTFTeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string CommentText { get; set; }
        public int ProductId { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
