//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTFPrice_HTFTeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public string ContactName { get; set; }
        public string Email { get; set; }
        public string ContactAddress { get; set; }
        public string ContactPhone { get; set; }
        public string UserId { get; set; }
        public string FullText { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool Status { get; set; }
    }
}
