//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTFPrice_HTFTeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Short { get; set; }
        public string FullText { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ViewCount { get; set; }
        public string Author { get; set; }
        public string HomeImageUrl { get; set; }
        public bool ShowOnHomePage { get; set; }
        public bool Published { get; set; }
    
        public virtual NewsCategory NewsCategory { get; set; }
    }
}
