//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTFPrice_HTFTeam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public string ContactName { get; set; }
        public string Email { get; set; }
        public string ContactAddress { get; set; }
        public string ContactPhone { get; set; }
        public bool Status { get; set; }
        [Display(Name = "Message")]
        public string Note { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}")]
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
