//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTFPrice_HTFTeam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ProductDetail
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        [Display(Name = "Index")]
        public int DisplayOrder { get; set; }
        public string PropertyName { get; set; }
        public string PropertyValue { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
